# Generated by Django 4.2.5 on 2023-09-05 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Waggle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waggleText', models.TextField(blank=True, null=True)),
                ('waggleImage', models.FileField(blank=True, null=True, upload_to='images/')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WaggleLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('waggle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Waggles.waggle')),
            ],
        ),
        migrations.AddField(
            model_name='waggle',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='waggle_user', through='Waggles.WaggleLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='waggle',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Waggles.waggle'),
        ),
        migrations.AddField(
            model_name='waggle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
