# Generated by Django 4.2.4 on 2023-08-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Waggle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waggleText', models.TextField(blank=True, null=True)),
                ('waggleImage', models.FileField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
