# Generated by Django 4.2.4 on 2023-08-19 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Waggles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waggle',
            options={'ordering': ['-id']},
        ),
    ]
