# Generated by Django 4.2.5 on 2023-10-21 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Waggles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waggle',
            old_name='time_stamp',
            new_name='timestamp',
        ),
    ]
