# Generated by Django 4.2.5 on 2023-11-24 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Waggles', '0002_rename_time_stamp_waggle_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waggle',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Waggles.waggle'),
        ),
    ]
